### ISSUE TITLE
A few enhancements I found on your page.

### ISSUE THREAD

**Issue by joshi-chinmay** [chznbaum/rails-portfolio#16]
On your [about](https://chazonabaum.com/about) page, if you click on the buttons, without closing the first opened content, things start to pile up, which are adding a big scroll on the page. You might not want that to happen.

Also, there's a horizontal scroll present on the page. I can see that `.site-wrapper` is your parent `div`. You can simply replace that with `.container-fluid`.
Or, you need to improve styling for `background` and `background-overlay` classes. They are adding the horizontal scroll.

**Comment by chznbaum** [comment]
I'm sorry for the delayed response.

Thank you for your feedback! I agree full-heartedly with the comments you made, and I'd been planning to re-do the front-end of the site, especially to remove the Bootstrap.

Since the site's in the middle of a reno and the classes causing the issue no longer exist, I'm going to close this issue.
